### PR TITLE
Packing Inline Arrays now correctly stores instance for structs.

### PR DESCRIPTION
**Pull request by lundmark**
This fixes the bug where structs in inline arrays have pointers that are not patched correctly.

### CODE REVIEW

**Comment by lundmark** [comment]
Solves https://github.com/wc-duck/datalibrary/issues/36

**Comment by wc-duck** [comment]
PR is missing unittest capturing issue.

**Comment by wc-duck** [comment]
I'll merge this now and add tests.

**Comment by lundmark** [comment]
Thanks :)

**Pull request merged**
